version: '3.8'
services:
  quiz-web:
    image: nginx:latest
    container_name: capm-quiz
    ports:
      - "8081:80"
    volumes:
      - /volume1/Exam_Prep/html:/usr/share/nginx/html:ro
    restart: unless-stopped